name: Python Test with Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv sync --dev --python $(which python)
        pipenv shell --fancy --python $(which python)

    # Run tests and coverage for web-app
    - name: Test with pytest (web-app)
      run: |
        cd web-app
        pipenv run coverage run -m pytest
        pipenv run coverage report

    # Run tests and coverage for machine-learning-client
    - name: Test with pytest (machine-learning-client)
      run: |
        cd machine-learning-client
        pipenv run coverage run -m pytest
        pipenv run coverage report
